import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                serif: ['Playfair Display', ...defaultTheme.fontFamily.serif],
                'label-md': ['Inter'],
                'label-sm': ['Inter'],
                'headline-lg': ['Playfair Display'],
                'headline-md': ['Playfair Display'],
                'body-lg': ['Inter'],
                'body-md': ['Inter'],
                'body-sm': ['Inter'],
                'display-lg': ['Playfair Display'],
            },
            colors: {
                'surface-container-high': '#e7e8e9',
                'tertiary-fixed': '#e4e2e1',
                'on-secondary-fixed-variant': '#5d4201',
                'surface-variant': '#e1e3e4',
                'on-primary': '#ffffff',
                'surface-container': '#edeeef',
                'background': '#f8f9fa',
                'surface': '#f8f9fa',
                'on-tertiary-container': '#939292',
                'surface-bright': '#f8f9fa',
                'tertiary-container': '#2b2b2b',
                'secondary-fixed-dim': '#e9c176',
                'surface-container-low': '#f3f4f5',
                'on-primary-fixed': '#081b3a',
                'error-container': '#ffdad6',
                'on-surface': '#191c1d',
                'on-secondary-container': '#785a1a',
                'primary': '#031635',
                'on-secondary-fixed': '#261900',
                'on-error-container': '#93000a',
                'on-secondary': '#ffffff',
                'tertiary': '#161717',
                'surface-dim': '#d9dadb',
                'outline-variant': '#c5c6cf',
                'inverse-surface': '#2e3132',
                'on-tertiary-fixed': '#1b1c1c',
                'primary-container': '#1a2b4b',
                'inverse-on-surface': '#f0f1f2',
                'on-tertiary': '#ffffff',
                'tertiary-fixed-dim': '#c8c6c6',
                'on-surface-variant': '#44474e',
                'secondary-fixed': '#ffdea5',
                'outline': '#75777f',
                'on-primary-fixed-variant': '#364768',
                'primary-fixed': '#d8e2ff',
                'secondary-container': '#fed488',
                'secondary': '#775a19',
                'surface-container-lowest': '#ffffff',
                'surface-container-highest': '#e1e3e4',
                'on-primary-container': '#8293b8',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'on-tertiary-fixed-variant': '#474747',
                'on-background': '#191c1d',
                'primary-fixed-dim': '#b6c6ef',
                'surface-tint': '#4e5e81',
                'inverse-primary': '#b6c6ef',
            },
            spacing: {
                'xs': '4px',
                'sm': '8px',
                'md': '16px',
                'lg': '24px',
                'xl': '32px',
                '2xl': '48px',
                '3xl': '64px',
            },
            fontSize: {
                'label-md': ['14px', { 'lineHeight': '1.2', 'letterSpacing': '0.01em', 'fontWeight': '600' }],
                'label-sm': ['12px', { 'lineHeight': '1.2', 'fontWeight': '500' }],
                'headline-lg': ['32px', { 'lineHeight': '1.3', 'fontWeight': '700' }],
                'headline-md': ['24px', { 'lineHeight': '1.4', 'fontWeight': '600' }],
                'body-lg': ['18px', { 'lineHeight': '1.6', 'fontWeight': '400' }],
                'body-md': ['16px', { 'lineHeight': '1.5', 'fontWeight': '400' }],
                'body-sm': ['14px', { 'lineHeight': '1.5', 'fontWeight': '400' }],
                'display-lg': ['48px', { 'lineHeight': '1.2', 'letterSpacing': '-0.02em', 'fontWeight': '700' }],
            },
        },
    },

    plugins: [forms],
};
